# https://github.com/datajoint/mysql-docker/blob/729cb45bf74d2dfd015d7ac1d504165f82a99c44/docker-compose.yaml
# Example of docker-based Database Server.
# Start using: docker-compose up -d
# Stop using: docker-compose down
services:
  arash-datajoint-db:
    image: datajoint/mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=pose
    ports:
      - "3306:3306"
    volumes:
      ## persist data across docker-compose up/down
      - /media1/data/arash/benchtrack/datajoint_database/:/var/lib/mysql
    restart: always
